
namespace Copper.ViewManager
{
	/// <summary>
    /// Collection of view IDs for use with the ViewManager's Add and Remove functions
    /// </summary>
    /// <remarks>
    /// This class is auto-generated and can be regenerated by clicking the button found in the ViewRegistrar
    /// </remarks>
	public static class View
	{
		public const int MainMenu = 442195652;
		public const int GameHUD = -337189145;
		public const int SettingsView = 358662898;
		public const int ConfirmationDialog = -669765921;
	}
}
