
namespace Copper.ViewManager
{
	/// <summary>
    /// Collection of view IDs for use with the ViewManager's Add and Remove functions
    /// </summary>
    /// <remarks>
    /// This class is auto-generated and can be regenerated by clicking the button found in the ViewRegistrar
    /// </remarks>
	public static class View
	{
		public const int Test1 = -1556460260;
		public const int Test2 = -1556460257;
		public const int Test3 = -1556460258;
	}
}
