
namespace Copper.ViewManager
{
	/// <summary>
    /// Collection of Layer IDs for use with the ViewManager's layer lookup functions
    /// </summary>
    /// <remarks>
    /// This class is auto-generated and can be regenerated by clicking the button found in the ViewRegistrar
    /// </remarks>
	public static class Layer
	{
		public const int Main = 0;
		public const int HUD = 1;
		public const int Settings = 2;
	}
}
